services:
  bot:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      BACKEND_URL: ${BACKEND_URL}
      SERVICE_KEY: ${SERVICE_KEY}
      VERIFY_TOKEN: ${VERIFY_TOKEN}
      APP_SECRET: ${APP_SECRET}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      WABA_PHONE_NUMBER_ID: ${WABA_PHONE_NUMBER_ID}
      GRAPH_API_VERSION: ${GRAPH_API_VERSION}